Repository Gilles-Maurer-Organization/AI50_patrolling, pull requests merged in 2024-12, with the labels that each got.

#38 Popups
  assets/popup/check-mark.png
  assets/popup/error.png
  assets/popup/information.png
  constants/Colors.py
  controllers/GraphController.py
  controllers/buttons/StartButtonController.py
  services/CompleteGraphService.py
  views/GraphView.py
  views/popup/ErrorPopupView.py
  views/popup/InfoPopupView.py
  views/popup/PopupView.py
Labels: enhancement

#45 GraphData auxiliary structure
  controllers/GraphController.py
  controllers/buttons/StartButtonController.py
  models/GraphData.py
  models/GraphDataComplements.py
  services/CSVService.py
  services/ICSVService.py
  tests/test_GraphController.py
Labels: maintainability

#47 Hotfix: edges creation
  controllers/NodeController.py
Labels: bug

#50 Evolutional Algorithm
  .DS_Store
  check_eulerian.py
  models/Graph.py
  services/algorithms/EvolutionalAlgorithm.py
Labels: enhancement

#59 fix: window size
  constants/Config.py
Labels: invalid

#64 code update in population generation
  services/algorithms/EvolutionalAlgorithm.py
Labels: bug

#65 K means algorithm
  services/algorithms/KMeans.py
  services/algorithms/KMeansEvolutionalAlgorithm.py
Labels: enhancement

#71 Naive Algorithm
  models/algorithms/Naive.py
  services/algorithms/NaiveAlgorithm.py
  services/algorithms/NaiveAlgorithmRT.py
Labels: enhancement

#54 Alignment assistant
  assets/checkbox/tick.png
  controllers/AlignmentCheckBoxController.py
  controllers/GraphController.py
  controllers/NodeController.py
  controllers/ParametersController.py
  controllers/ScrollingListController.py
  models/AlignmentCheckBox.py
  models/Graph.py
  views/AlignmentCheckBoxView.py
  views/GraphView.py
  views/ScrollingListView.py
Labels: enhancement

#84 feat: Agent image
  controllers/GraphController.py
  controllers/SimulationController.py
  views/AgentView.py
  views/GraphView.py
Labels: enhancement

#80 Import graph image crash
  controllers/FileExplorerController.py
  controllers/GraphController.py
  controllers/buttons/ButtonController.py
Labels: bug

#89 fix: Column algorithm parameters
  controllers/text_boxes/AlgorithmParametersController.py
  tests/test_AlgorithmParametersController.py
Labels: enhancement

#86 Display simulation idleness
  controllers/IdlenessesController.py
  controllers/SimulationDataController.py
  controllers/ViewController.py
  models/IdlenessData.py
  views/IdlenessView.py
  views/SimulationDataView.py
Labels: enhancement

#96 fix: Popup user management
  .gitignore
  backgrounds/im1.jpg
  backgrounds/image1.jpg
  controllers/FileExplorerController.py
  controllers/GraphController.py
  controllers/buttons/StartButtonController.py
  models/Error.py
  models/Info.py
  views/GraphView.py
Labels: enhancement

#108 Fix: Textbox number deletion
  controllers/text_boxes/AlgorithmParametersController.py
  controllers/text_boxes/BaseTextBoxController.py
  models/TextBox.py
Labels: invalid

#104 Repair evolutional algorithm
  .DS_Store
  services/algorithms/EvolutionalAlgorithm.py
Labels: invalid

#110 Feat: Back to configuration button
  assets/widgets/clear.png
  assets/widgets/import.png
  assets/widgets/number_agents.png
  assets/widgets/save.png
  assets/widgets/scrolling_icon.png
  constants/Colors.py
  controllers/IdlenessesController.py
  controllers/SimulationDataController.py
  controllers/ViewController.py
  controllers/buttons/BackButtonController.py
  controllers/buttons/BaseButtonController.py
  controllers/buttons/ButtonController.py
  controllers/buttons/StartButtonController.py
  controllers/text_boxes/TextBoxController.py
  views/AlignmentCheckBoxView.py
  views/ButtonView.py
  views/IdlenessView.py
  views/ScrollingListView.py
  views/text_boxes/BaseTextBoxView.py
Labels: enhancement, maintainability

#113 fix bug placement centers
  services/algorithms/KMeansAlgorithm.py
Labels: bug
