Repository Gilles-Maurer-Organization/AI50_patrolling, pull requests merged in 2025-01, with the labels that each got.

#114 fix: Threading & flashing popups
  controllers/buttons/StartButtonController.py
  services/algorithms/KMeansEvolutionalAlgorithm.py
  views/popup/PopupView.py
Labels: enhancement

#118 hotfix: Reset idlenesses & export thread
  controllers/GraphController.py
  controllers/IdlenessesController.py
  controllers/NodeController.py
  controllers/SimulationController.py
  controllers/SimulationDataController.py
  controllers/buttons/BackButtonController.py
  main.py
  models/IdlenessData.py
  services/CSVService.py
  services/ICSVService.py
  views/IdlenessView.py
Labels: bug, invalid

#116 Improve Evolutional Algorithm
  services/algorithms/EvolutionalAlgorithm.py
Labels: enhancement

#120 Naive algorithm runtime
  controllers/ScrollingListController.py
  controllers/SimulationController.py
  controllers/buttons/StartButtonController.py
  models/Agent.py
  models/algorithms/NaiveRuntime.py
  services/algorithms/NaiveAlgorithm.py
  services/algorithms/NaiveAlgorithmRT.py
  services/algorithms/NaiveAlgorithmRuntime.py
Labels: enhancement, coverage

#123 Feat: README
  README.md
Labels: documentation

#125 fixing the agent class' docstring
  models/Agent.py
Labels: documentation

#129 Fix: README
  README.md
Labels: documentation

#132 feat: CD pipeline
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: enhancement

#133 fix: Upgrade of the decisions of all agents in the Naive alogrithm RT
  services/algorithms/NaiveAlgorithmRuntime.py
Labels: enhancement

#137 Fix: CD pipeline
  .github/workflows/cd.yml
  README.md
Labels: invalid

#140 fix: README
  README.md
Labels: enhancement

#143 Fix: README
  README.md
Labels: documentation

#146 feat: Analyse executable in CD pipeline
  .github/workflows/cd.yml
Labels: enhancement

#148 feat: Analyse Executable
  .github/workflows/cd.yml
Labels: enhancement
